import type { Metadata } from "next";

import "./globals.css";
import "./mdx.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "FOSO",
  description: "Generated by FOSO",
};

export default function BLogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased scroll-smooth min-h-screen relative z-[1000] overflow-y-scroll`}>
        <div className="absolute mt-[6rem] -z-10 -left-[1rem] h-[31.25rem] w-[40.25rem] rounded-full blur-[10rem] sm:w-[30.75rem] ">
          <span className="absolute inset-0 bg-gradient-to-r from-[#E0FFCC] to-[#CCFFEC] blur-[72px]"></span>
        </div>
        <div className="absolute bottom-[10rem] right-[1rem] -z-10 h-[30.25rem] w-[30.25rem] rounded-full blur-[10rem] sm:w-[30.75rem]">
          <span className="absolute inset-0 bg-gradient-to-r from-[#E0FFCC] to-[#CCFFEC] blur-[72px]"></span>
        </div>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
